dependencies:
  - aave/protocol-v2@1.0.1
compiler:
  solc:
    remappings:
      - '@aave=aave/protocol-v2@1.0.1'
networks:
  kovan:
    weth_token: "0xd0a1e359811322d97991e03f863a0c30c2cf029c"
    lending_pool_address_provider: "0x88757f2f99175387ab4c6a4b3067c77a695b0349"
  mainnet-fork:
    weth_token: "0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2"
    lending_pool_address_provider: "0xb53c1a33016b2dc2ff3653530bff1848a515c8c5"
wallets:
  from_mnemonic: ${MNEMONIC}
dotenv: .env